# -*- coding: utf-8 -*-
"""classificacao_etaria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q5eW-Tq-11uFEcb0a-A98Kz8Xw5Duc8h
"""

idade = int(input("Digite sua idade : \n"))

print(f"Você tem {idade} anos\n")

if (idade < 10):
    print("Você só pode ver programas com a classificação 'LIVRE' ")

elif (idade >= 10 and idade < 12):
    print("Você só pode ver programas até a classificação '10' ")

elif  (idade >= 12 and idade < 14):
    print("Você só pode ver programas até a classificação '12' ")

elif (idade >= 14 and idade < 16):
    print("Você só pode ver programas até a classificação '14' ")

elif (idade >= 16 and idade < 18):
    print("Você só pode ver programas até a classificação '16' ")

else:
    print("Você pode ver todos os programas")